### ISSUE TITLE
您好，阿里云国际版无法获取到ip

### ISSUE THREAD

**Issue by q465427587** [1715173329/mtproto-onekey#1]
[OK]系统组件更新成功。
正在生成基础信息中...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (6) Could not resolve host: ipinfo.io
[Error]读取vps_ip失败！
正在卸载中...
Failed to stop mtproto.service: Unit mtproto.service not loaded.
Failed to execute operation: No such file or directory
[OK]MTProto卸载成功

**Comment by q465427587** [comment]
Ubuntu 16.04.4 LTS

**Comment by 1715173329** [comment]
您好，我现在已经新增 [ip.sb](https://api.ip.sb/ip) 源，现在可以再尝试一下。

**Comment by 1715173329** [comment]
同时建议检查一下您的DNS。

**Comment by 1715173329** [comment]
如果 问题仍然存在 或是 能够正常使用了 ，麻烦通知我一下，谢谢。
